language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install .

script:
  - python setup.py test
  - lsapopulate 'data/froac/**/*.xml'
  - lsapopulate 'data/isi/**/*.txt'
  - lsamodel
  - lsaquery find
