language: python

python:
  - "3.6"

cache:
  pip: true
  apt: true
  directories:
    - $HOME/.nltk_data

install:
  - pip --quiet install .
  - condor utils preparedb -y

before_script:
  - python -m nltk.downloader snowball_data stopwords

script:
  - python setup.py test
  - condor bibliography create froac data/froac/**/*.xml
  - condor bibliography create isi data/isi/*.txt
  - condor model create
  - condor query find
  - condor bibliography
  - condor matrix
  - condor ranking
