# Site settings
title: condor-ir
email: odarbelaeze@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    condor-ir is an information retrieval software project, it provides
    infrastructure to create bibliography sets, term document matrices and also
    index and query the information withing the bobliography sets.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://home.condor-ir.co"
twitter_username: odarbelaeze
github_username:  odarbelaeze

# Build settings
markdown: kramdown
